# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://mydomain.com'
baseurl: ''
title: 'My website'
description: 'This is my new website'
permalink: pretty
logo: "https://www.gravatar.com/avatar/6c0377abcf4da91cdd35dea4554b2a4c?s=52"

# Pagination
paginate: 10
paginate_path: news/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: Research
  url: /research/
- title: Publications
  url: /publications/
- title: People
  url: /people/
- title: Programs
  url: /programs/
- title: News
  url: /news/
- title: Teaching
  url: /teaching/
- title: C.A.M.P
  url: /camp/
# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  news:
    title: Posts
    output: true
    description: "something catchy goes here.."
    feature_text: |
      News
    feature_image: "https://picsum.photos/2560/600?image=866"
