# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'http://zeagenomics.org'
baseurl: ''
title: 'Hufford Lab'
description: 'Evolutionary genomics of maize and its wild relatives'
permalink: pretty
logo: 

# Pagination
paginate: 5
paginate_path: news/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: Research
  url: /research/
- title: Publications
  url: /publications/
- title: People
  url: /people/
- title: News
  url: /news/
- title: Teaching
  url: /teaching/
- title: C.A.M.P.
  url: /camp/
# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    output: true
    description: "<b>Notable events in the Hufford Lab</b>"
    feature_text: |
      ## <span style="color:white">News</span>
    feature_image: "https://huffordlab.github.io/pictures/maize.jpg"
